
[[constraint]]
  name = "github.com/fatih/color"
  version = "1.9.0"

[[constraint]]
  name = "github.com/gdamore/tcell"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/rivo/tview"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[prune]
  go-tests = true
  unused-packages = true
